sudo: required
services:
    - docker

before_install:
    - docker build -t paulo/docker-mac -f Dockerfile.dev .

script:
    - docker run -e CI=true paulo/docker-mac npm run test -- --coverage

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "Docker-React"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-311970152278"
    bucket_path: "Docker-React" 
    on:
     branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
     secure: $AWS_SECRET_KEY

     
